### ISSUE TITLE
Page can't be loaded in valaxy v0.14.3

### ISSUE THREAD

**Issue by Seanium** [YunYouJun/valaxy#167] opened 2023-02-01 04:12 UTC
I deployed valaxy v0.14.3 by default settings in https://github.com/Seanium/Seanium.github.io, but page can't be loaded. Only one file will pop up for download. See https://seanium.github.io/.
![图片](https://user-images.githubusercontent.com/10975821/215942810-6b0375d2-5519-4789-9c01-39bc5c635876.png)
![图片](https://user-images.githubusercontent.com/10975821/215942855-a6845ceb-572b-4515-8599-69cdd31b504f.png)

**Comment by YunYouJun** [comment] 2023-02-01 16:55
I once met a similar problem, it seems and making relevant `gh-pages`, use `vercel`/`netlify`/`cloudflare` deployment can be normal.

**Comment by YunYouJun** [comment] 2023-02-01 17:11
This is caused by `Content-Type: application/octet-stream`. (gh-pages)

**Comment by Seanium** [comment] 2023-02-02 01:42
I see. Thank you.

**Comment by YunYouJun** [comment] 2023-02-03 03:38
I will try to find the reason of gh-pages set it as `application/octet-stream`.

**Comment by YunYouJun** [comment] 2023-02-04 19:35
I create https://github.com/YunYouJun/valaxy/commit/07039f81f40153865104dc8f228378ac320bdec9 to fix bugs caused by [vite-plugin-vue-layouts](https://github.com/JohnCampionJr/vite-plugin-vue-layouts).
It will be released in `v0.14.6`.

I also create a PR for vite-plugin-vue-layouts, just wait it be merged.

https://github.com/JohnCampionJr/vite-plugin-vue-layouts/pull/97

**Comment by YunYouJun** [comment] 2023-02-04 21:14
Troubleshooting log: https://github.com/YunYouJun/valaxy/discussions/170

I will closed this issue when https://github.com/JohnCampionJr/vite-plugin-vue-layouts/pull/97 merged.

**Closed** 2023-02-19 04:30 UTC
Labels: bug, help wanted, upstream
