### ISSUE TITLE
bug: theme pnpm demo needs to refresh the page for the first time

### ISSUE THREAD

**Issue by TuiMao233** [YunYouJun/valaxy#105] opened 2022-08-02 07:24 UTC
The page opened after theme pnpm demo is blank, you need to refresh the page once

![image](https://user-images.githubusercontent.com/49724027/182316388-3d3956a2-c643-46a6-b37d-8471aea391a0.png)

**Comment by YunYouJun** [comment] 2022-10-03 11:20
Can't reproduce. We need more information.

**Comment by YunYouJun** [comment] 2023-01-22 17:54
Close without more information. Perhaps it has been fixed in the new version.

**Closed by YunYouJun** 2023-01-22 17:54 UTC
